### ISSUE TITLE
problem with windows line breaks

### ISSUE THREAD

**Issue by odr** [23Skidoo/raw-strings-qq#1]
On Windows you have to remove '\r' to make it the same as regular string.
You can't see the difference in ghci but if you make constants in external file you get it.
x = unlines ["a","b"]
y=[r|a
b
|]

then
ghci> x
"a\nb\n"
ghci>y
"a\r\nb\r\n"

This quote is works right for me:
quoteExp = litE . stringL . filter (/= chr 13)

**Comment by 23Skidoo** [comment]
Not sure whether this is actually a bug. After all, a user may actually want the raw string to have Windows line endings.

I'll look at what Python and C++ are doing.

**Comment by 23Skidoo** [comment]
Thought a bit more about this. Version control systems (e.g. Git) usually store text files using Unix line endings, but allow checking them out in a platform-specific format. Therefore it makes sense to treat `\r\n` specially for cross-platform consistency.

**Comment by 23Skidoo** [comment]
Fixed, fix released on Hackage. Also reported this issue on the GHC bug tracker: https://ghc.haskell.org/trac/ghc/ticket/11215.

**Comment by 23Skidoo** [comment]
Python apparently also normalises line endings in raw string literals.
